-- Admin users table
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'editor', 'viewer')),
  is_active BOOLEAN DEFAULT TRUE,
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Admin sessions table
CREATE TABLE IF NOT EXISTS admin_sessions (
  id TEXT PRIMARY KEY,
  user_id BIGINT REFERENCES admin_users NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Insert default admin user (password: admin123)
INSERT INTO admin_users (email, password_hash, full_name, role) VALUES
('admin@learnvow.com', '$2b$10$rVv.F.Ra5GqHHTRM8pV1UeH8.HpXyDQ4y6GQb9s2P4zZ9z5Zz5Zz5', 'Administrator', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Enhanced content management tables with proper indexes

-- Authors table
CREATE TABLE IF NOT EXISTS authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bio TEXT,
  photo_url TEXT,
  website TEXT,
  created_at TIMESTAMP WITH TIME Z ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  icon_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Publishers table
CREATE TABLE IF NOT EXISTS publishers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  website TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Content table (enhanced)
CREATE TABLE IF NOT EXISTS content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  cover_url TEXT,
  content_type TEXT NOT NULL CHECK (content_type IN ('ebook', 'audiobook')),
  file_urls JSONB,
  sample_url TEXT,
  author_id BIGINT REFERENCES authors NOT NULL,
  publisher_id BIGINT REFERENCES publishers,
  category_id BIGINT REFERENCES categories,
  isbn TEXT,
  pages INTEGER,
  duration INTEGER,
  language TEXT DEFAULT 'en',
  tags TEXT[],
  price NUMERIC(10,2) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Reviews table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  content_id BIGINT REFERENCES content NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title TEXT,
  review TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  UNIQUE(user_id, content_id)
);

-- User subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  plan_id BIGINT NOT NULL,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'cancelled', 'expired')),
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  cancel_date TIMESTAMP WITH TIME ZONE,
  auto_renew BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Subscription plans table
CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  interval TEXT NOT NULL CHECK (interval IN ('month', 'year')),
  features JSONB,
  max_books INTEGER,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Gift cards table
CREATE TABLE IF NOT EXISTS gift_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  balance NUMERIC(10,2) NOT NULL,
  initial_balance NUMERIC(10,2) NOT NULL,
  recipient_email TEXT,
  sender_name TEXT,
  message TEXT,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_redeemed BOOLEAN DEFAULT FALSE,
  redeemed_by UUID REFERENCES auth.users,
  redeemed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_content_author ON content(author_id);
CREATE INDEX IF NOT EXISTS idx_content_category ON content(category_id);
CREATE INDEX IF NOT EXISTS idx_content_publisher ON content(publisher_id);
CREATE INDEX IF NOT EXISTS idx_content_type ON content(content_type);
CREATE INDEX IF NOT EXISTS idx_content_active ON content(is_active);
CREATE INDEX IF NOT EXISTS idx_reviews_content ON reviews(content_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_gift_cards_code ON gift_cards(code);
CREATE INDEX IF NOT EXISTS idx_gift_cards_redeemed ON gift_cards(is_redeemed);

-- Insert sample data

-- Sample authors
INSERT INTO authors (name, bio, website) VALUES
('J.K. Rowling', 'British author, best known for the Harry Potter series', 'https://jkrowling.com'),
('George Orwell', 'English novelist, essayist, journalist and critic', 'https://georgeorwell.com'),
('Agatha Christie', 'English writer known for her detective novels', 'https://agathachristie.com')
ON CONFLICT DO NOTHING;

-- Sample categories
INSERT INTO categories (name, slug, description) VALUES
('Fiction', 'fiction', 'Fictional stories and novels'),
('Non-Fiction', 'non-fiction', 'Factual books and biographies'),
('Science Fiction', 'sci-fi', 'Science fiction and fantasy novels'),
('Mystery', 'mystery', 'Mystery and thriller books')
ON CONFLICT (slug) DO NOTHING;

-- Sample publishers
INSERT INTO publishers (name, website) VALUES
('Penguin Random House', 'https://penguinrandomhouse.com'),
('HarperCollins', 'https://harpercollins.com'),
('Simon & Schuster', 'https://simonandschuster.com')
ON CONFLICT DO NOTHING;

-- Sample content
INSERT INTO content (title, subtitle, description, content_type, price, author_id, category_id, publisher_id, isbn, pages, language) VALUES
('Harry Potter and the Philosopher''s Stone', 'First in the series', 'The first book in the Harry Potter series', 'ebook', 9.99, 1, 3, 1, '9780747532699', 223, 'en'),
('1984', 'A dystopian social science fiction novel', 'A dystopian social science fiction novel and cautionary tale', 'ebook', 7.99, 2, 1, 2, '9780451524935', 328, 'en'),
('Murder on the Orient Express', 'A Hercule Poirot Mystery', 'A detective novel by Agatha Christie', 'ebook', 8.99, 3, 4, 3, '9780062693662', 256, 'en')
ON CONFLICT DO NOTHING;

-- Sample subscription plans
INSERT INTO subscription_plans (name, description, price, interval, features, max_books) VALUES
('Basic', 'Access to standard library', 9.99, 'month', '{"max_downloads": 5, "max_devices": 2, "support": "email"}', 100),
('Premium', 'Full access to all books and features', 14.99, 'month', '{"max_downloads": 20, "max_devices": 5, "support": "priority", "offline_reading": true}', 1000),
('Premium Yearly', 'Full access with 2 months free', 149.99, 'year', '{"max_downloads": 20, "max_devices": 5, "support": "priority", "offline_reading": true}', 1000)
ON CONFLICT DO NOTHING;