-- Additional tables for enhanced reading experience

-- Bookmarks table (already exists, but adding more fields)
alter table bookmarks 
add column if not exists highlight_color text default 'yellow',
add column if not exists annotation text;

-- Reading statistics table
create table reading_statistics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content_id bigint references content not null,
  time_spent integer default 0, -- in seconds
  pages_read integer default 0,
  last_read timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, content_id)
);

-- Highlight colors table
create table highlight_colors (
  id bigint generated by default as identity primary key,
  name text not null,
  hex_color text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default highlight colors
insert into highlight_colors (name, hex_color) values
  ('Yellow', '#FFEB3B'),
  ('Blue', '#2196F3'),
  ('Green', '#4CAF50'),
  ('Pink', '#E91E63'),
  ('Orange', '#FF9800'),
  ('Purple', '#9C27B0')
  on conflict (name) do nothing;

-- Reading goals table
create table reading_goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  goal_type text not null check (goal_type in ('daily', 'weekly', 'monthly', 'yearly')),
  target_value integer not null,
  current_value integer default 0,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, goal_type, start_date)
);

-- Indexes for better performance
create index if not exists idx_bookmarks_user on bookmarks(user_id);
create index if not exists idx_bookmarks_content on bookmarks(content_id);
create index if not exists idx_reading_stats_user on reading_statistics(user_id);
create index if not exists idx_reading_stats_content on reading_statistics(content_id);
create index if not exists idx_reading_goals_user on reading_goals(user_id);
create index if not exists idx_reading_goals_type on reading_goals(goal_type);